language: generic

sudo: required

services:
  - docker

before_install:
  - docker-compose build

script:
  - docker-compose run django python manage.py test

after_success:
  - docker build -t gimkuku/nginx ./nginx
  - docker build -f ./django/Dockerfile . -t gimkuku/django

  #도커 허브 로그인
  #아이디는 travis CI 홈페이지에 미리 넣어준다.
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin
  #빌드된 이미지들을 도커 허브에 push
#  - docker-compose push
  - docker push gimkuku/django
  - docker push gimkuku/nginx

deploy:
  #외부 서비스 표시(s3, elesticbeanstalk, firebase 등등)
  provider: elasticbeanstalk
  #현재 사용하고 있는 AWS의 서비스가 위치하고있는 물리 장소
  region: "ap-northeast-2"
  #생성된 어플리케이션의 이름
  app: "venti"
  #elasticbeanstalk을 위한 s3 버켓이름
  env: "Venti-env-1"
  bucket_name: elasticbeanstalk-ap-northeast-2-893665225040
  bucket_path: "venti"
  #특정 branch에만 해당 aws서버에 올릴 수 있게 설정해두었다.
  on:
    branch: main
  # iam 계정으로 부터 생성해서 travis ci에 저장해둔 key
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
