# Generated by Django 3.1.4 on 2021-07-20 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_notification_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.brand'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.event'),
        ),
    ]
