# Generated by Django 3.1.4 on 2021-07-25 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210720_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='default', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='due',
            field=models.DateTimeField(null=True),
        ),
    ]
